import type { Shortcut } from '../types';

export const DEFAULT_SHORTCUTS: Record<string, Shortcut> = {
	toggleSidebar: {
		id: 'toggleSidebar',
		label: 'Toggle Left Panel',
		keys: ['Alt', 'Meta', 'ArrowLeft'],
		scope: 'window',
	},
	toggleRightPanel: {
		id: 'toggleRightPanel',
		label: 'Toggle Right Panel',
		keys: ['Alt', 'Meta', 'ArrowRight'],
		scope: 'window',
	},
	cyclePrev: { id: 'cyclePrev', label: 'Previous Agent', keys: ['Meta', '['], scope: 'window' },
	cycleNext: { id: 'cycleNext', label: 'Next Agent', keys: ['Meta', ']'], scope: 'window' },
	navBack: { id: 'navBack', label: 'Navigate Back', keys: ['Meta', 'Shift', ','], scope: 'window' },
	navForward: {
		id: 'navForward',
		label: 'Navigate Forward',
		keys: ['Meta', 'Shift', '.'],
		scope: 'window',
	},
	newInstance: { id: 'newInstance', label: 'New Agent', keys: ['Meta', 'n'], scope: 'window' },
	newGroupChat: {
		id: 'newGroupChat',
		label: 'New Group Chat',
		keys: ['Alt', 'Meta', 'c'],
		scope: 'window',
	},
	killInstance: {
		id: 'killInstance',
		label: 'Remove',
		keys: ['Meta', 'Shift', 'Backspace'],
		scope: 'window',
	},
	moveToGroup: {
		id: 'moveToGroup',
		label: 'Move Session to Group',
		keys: ['Meta', 'Shift', 'm'],
		scope: 'window',
	},
	toggleMode: {
		id: 'toggleMode',
		label: 'Switch AI/Shell Mode',
		keys: ['Meta', 'j'],
		scope: 'window',
	},
	quickAction: { id: 'quickAction', label: 'Quick Actions', keys: ['Meta', 'k'], scope: 'global' },
	help: { id: 'help', label: 'Show Shortcuts', keys: ['Meta', '/'], scope: 'global' },
	settings: { id: 'settings', label: 'Open Settings', keys: ['Meta', ','], scope: 'global' },
	agentSettings: {
		id: 'agentSettings',
		label: 'Open Agent Settings',
		keys: ['Alt', 'Meta', ','],
		scope: 'window',
	},
	goToFiles: {
		id: 'goToFiles',
		label: 'Go to Files Tab',
		keys: ['Meta', 'Shift', 'f'],
		scope: 'window',
	},
	goToHistory: {
		id: 'goToHistory',
		label: 'Go to History Tab',
		keys: ['Meta', 'Shift', 'h'],
		scope: 'window',
	},
	goToAutoRun: {
		id: 'goToAutoRun',
		label: 'Go to Auto Run Tab',
		keys: ['Meta', 'Shift', '1'],
		scope: 'window',
	},
	copyFilePath: {
		id: 'copyFilePath',
		label: 'Copy File Path (in Preview)',
		keys: ['Meta', 'p'],
		scope: 'window',
	},
	toggleMarkdownMode: {
		id: 'toggleMarkdownMode',
		label: 'Toggle Edit/Preview',
		keys: ['Meta', 'e'],
		scope: 'window',
	},
	toggleAutoRunExpanded: {
		id: 'toggleAutoRunExpanded',
		label: 'Toggle Auto Run Expanded',
		keys: ['Meta', 'Shift', 'e'],
		scope: 'window',
	},
	focusInput: {
		id: 'focusInput',
		label: 'Toggle Input/Output Focus',
		keys: ['Meta', '.'],
		scope: 'window',
	},
	focusSidebar: {
		id: 'focusSidebar',
		label: 'Focus Left Panel',
		keys: ['Meta', 'Shift', 'a'],
		scope: 'window',
	},
	viewGitDiff: {
		id: 'viewGitDiff',
		label: 'View Git Diff',
		keys: ['Meta', 'Shift', 'd'],
		scope: 'window',
	},
	viewGitLog: {
		id: 'viewGitLog',
		label: 'View Git Log',
		keys: ['Meta', 'Shift', 'g'],
		scope: 'window',
	},
	agentSessions: {
		id: 'agentSessions',
		label: 'View Agent Sessions',
		keys: ['Meta', 'Shift', 'l'],
		scope: 'window',
	},
	systemLogs: {
		id: 'systemLogs',
		label: 'System Log Viewer',
		keys: ['Alt', 'Meta', 'l'],
		scope: 'global',
	},
	processMonitor: {
		id: 'processMonitor',
		label: 'System Process Monitor',
		keys: ['Alt', 'Meta', 'p'],
		scope: 'global',
	},
	usageDashboard: {
		id: 'usageDashboard',
		label: 'Usage Dashboard',
		keys: ['Alt', 'Meta', 'u'],
		scope: 'global',
	},
	jumpToBottom: {
		id: 'jumpToBottom',
		label: 'Jump to Bottom',
		keys: ['Meta', 'Shift', 'j'],
		scope: 'window',
	},
	prevTab: { id: 'prevTab', label: 'Previous Tab', keys: ['Meta', 'Shift', '['], scope: 'window' },
	nextTab: { id: 'nextTab', label: 'Next Tab', keys: ['Meta', 'Shift', ']'], scope: 'window' },
	openImageCarousel: {
		id: 'openImageCarousel',
		label: 'Open Image Carousel',
		keys: ['Meta', 'y'],
		scope: 'window',
	},
	toggleTabStar: {
		id: 'toggleTabStar',
		label: 'Toggle Tab Star',
		keys: ['Meta', 'Shift', 's'],
		scope: 'window',
	},
	openPromptComposer: {
		id: 'openPromptComposer',
		label: 'Open Prompt Composer',
		keys: ['Meta', 'Shift', 'p'],
		scope: 'window',
	},
	openWizard: {
		id: 'openWizard',
		label: 'New Agent Wizard',
		keys: ['Meta', 'Shift', 'n'],
		scope: 'global',
	},
	fuzzyFileSearch: {
		id: 'fuzzyFileSearch',
		label: 'Fuzzy File Search',
		keys: ['Meta', 'g'],
		scope: 'window',
	},
	toggleBookmark: {
		id: 'toggleBookmark',
		label: 'Toggle Bookmark',
		keys: ['Meta', 'Shift', 'b'],
		scope: 'window',
	},
};

// Non-editable shortcuts (displayed in help but not configurable)
export const FIXED_SHORTCUTS: Record<string, Shortcut> = {
	jumpToSession: {
		id: 'jumpToSession',
		label: 'Jump to Session (1-9, 0=10th)',
		keys: ['Alt', 'Meta', '1-0'],
		scope: 'window',
	},
	filterFiles: {
		id: 'filterFiles',
		label: 'Filter Files (in Files tab)',
		keys: ['Meta', 'f'],
		scope: 'window',
	},
	filterSessions: {
		id: 'filterSessions',
		label: 'Filter Sessions (in Left Panel)',
		keys: ['Meta', 'f'],
		scope: 'window',
	},
	filterHistory: {
		id: 'filterHistory',
		label: 'Filter History (in History tab)',
		keys: ['Meta', 'f'],
		scope: 'window',
	},
	searchLogs: {
		id: 'searchLogs',
		label: 'Search System Logs',
		keys: ['Meta', 'f'],
		scope: 'window',
	},
	searchOutput: {
		id: 'searchOutput',
		label: 'Search Output (in Main Window)',
		keys: ['Meta', 'f'],
		scope: 'window',
	},
	filePreviewBack: {
		id: 'filePreviewBack',
		label: 'File Preview: Go Back',
		keys: ['Meta', 'ArrowLeft'],
		scope: 'window',
	},
	filePreviewForward: {
		id: 'filePreviewForward',
		label: 'File Preview: Go Forward',
		keys: ['Meta', 'ArrowRight'],
		scope: 'window',
	},
};

// Tab navigation shortcuts (AI mode only) - all are window-scoped
export const TAB_SHORTCUTS: Record<string, Shortcut> = {
	tabSwitcher: {
		id: 'tabSwitcher',
		label: 'Tab Switcher',
		keys: ['Alt', 'Meta', 't'],
		scope: 'window',
	},
	newTab: { id: 'newTab', label: 'New Tab', keys: ['Meta', 't'], scope: 'window' },
	closeTab: { id: 'closeTab', label: 'Close Tab', keys: ['Meta', 'w'], scope: 'window' },
	closeAllTabs: {
		id: 'closeAllTabs',
		label: 'Close All Tabs',
		keys: ['Meta', 'Shift', 'w'],
		scope: 'window',
	},
	closeOtherTabs: {
		id: 'closeOtherTabs',
		label: 'Close Other Tabs',
		keys: ['Alt', 'Meta', 'w'],
		scope: 'window',
	},
	closeTabsLeft: {
		id: 'closeTabsLeft',
		label: 'Close Tabs to Left',
		keys: ['Meta', 'Shift', 'Alt', '['],
		scope: 'window',
	},
	closeTabsRight: {
		id: 'closeTabsRight',
		label: 'Close Tabs to Right',
		keys: ['Meta', 'Shift', 'Alt', ']'],
		scope: 'window',
	},
	reopenClosedTab: {
		id: 'reopenClosedTab',
		label: 'Reopen Closed Tab',
		keys: ['Meta', 'Shift', 't'],
		scope: 'window',
	},
	renameTab: {
		id: 'renameTab',
		label: 'Rename Tab',
		keys: ['Meta', 'Shift', 'r'],
		scope: 'window',
	},
	toggleReadOnlyMode: {
		id: 'toggleReadOnlyMode',
		label: 'Toggle Read-Only Mode',
		keys: ['Meta', 'r'],
		scope: 'window',
	},
	toggleSaveToHistory: {
		id: 'toggleSaveToHistory',
		label: 'Toggle Save to History',
		keys: ['Meta', 's'],
		scope: 'window',
	},
	toggleShowThinking: {
		id: 'toggleShowThinking',
		label: 'Toggle Show Thinking',
		keys: ['Meta', 'Shift', 'k'],
		scope: 'window',
	},
	filterUnreadTabs: {
		id: 'filterUnreadTabs',
		label: 'Filter Unread Tabs',
		keys: ['Meta', 'u'],
		scope: 'window',
	},
	toggleTabUnread: {
		id: 'toggleTabUnread',
		label: 'Toggle Tab Unread',
		keys: ['Meta', 'Shift', 'u'],
		scope: 'window',
	},
	moveToNewWindow: {
		id: 'moveToNewWindow',
		label: 'Move Tab to New Window',
		keys: ['Meta', 'Shift', 'o'],
		scope: 'window',
	},
	goToTab1: { id: 'goToTab1', label: 'Go to Tab 1', keys: ['Meta', '1'], scope: 'window' },
	goToTab2: { id: 'goToTab2', label: 'Go to Tab 2', keys: ['Meta', '2'], scope: 'window' },
	goToTab3: { id: 'goToTab3', label: 'Go to Tab 3', keys: ['Meta', '3'], scope: 'window' },
	goToTab4: { id: 'goToTab4', label: 'Go to Tab 4', keys: ['Meta', '4'], scope: 'window' },
	goToTab5: { id: 'goToTab5', label: 'Go to Tab 5', keys: ['Meta', '5'], scope: 'window' },
	goToTab6: { id: 'goToTab6', label: 'Go to Tab 6', keys: ['Meta', '6'], scope: 'window' },
	goToTab7: { id: 'goToTab7', label: 'Go to Tab 7', keys: ['Meta', '7'], scope: 'window' },
	goToTab8: { id: 'goToTab8', label: 'Go to Tab 8', keys: ['Meta', '8'], scope: 'window' },
	goToTab9: { id: 'goToTab9', label: 'Go to Tab 9', keys: ['Meta', '9'], scope: 'window' },
	goToLastTab: { id: 'goToLastTab', label: 'Go to Last Tab', keys: ['Meta', '0'], scope: 'window' },
};
