/**
 * Display tab searchable-settings entries.
 *
 * Part of the searchableSettings.ts domain-file split, mirroring the
 * settingsStore.ts / settingsMetadata.ts slice decomposition (see
 * settingsAnnotatorSlice.ts for that pattern).
 */

import { formatMetaKeyName } from '../../utils/shortcutFormatter';
import type { SearchableSetting } from './searchableSettings';

const META_KEY_NAME = formatMetaKeyName();

export const DISPLAY_SETTINGS: SearchableSetting[] = [
	{
		id: 'display-font-family',
		tab: 'display',
		tabLabel: 'Display',
		label: 'Font Family',
		description: 'Choose the font for the interface',
		keywords: ['font', 'typeface', 'family', 'monospace', 'custom font'],
	},
	{
		id: 'display-terminal-font-family',
		tab: 'display',
		tabLabel: 'Display',
		label: 'Terminal Font',
		description: 'Choose a font for the command terminal, independent of the UI font',
		keywords: [
			'font',
			'typeface',
			'terminal',
			'command terminal',
			'shell',
			'nerd font',
			'monospace',
			'zsh',
			'prompt',
		],
	},
	{
		id: 'display-font-size',
		tab: 'display',
		tabLabel: 'Display',
		label: 'Font Size',
		description: 'Small, Medium, Large, or X-Large',
		keywords: ['font', 'size', 'text', 'small', 'medium', 'large', 'x-large', 'xl', 'zoom'],
	},
	{
		id: 'display-max-log-buffer',
		tab: 'display',
		tabLabel: 'Display',
		label: 'Maximum Log Buffer',
		description: 'Maximum number of entries to retain for history and system log viewer',
		keywords: ['log', 'buffer', 'history', 'entries', 'limit', 'memory'],
	},
	{
		id: 'display-max-output-lines',
		tab: 'display',
		tabLabel: 'Display',
		label: 'Max Output Lines per Response',
		description: 'Long outputs will be collapsed into a scrollable window',
		keywords: ['output', 'lines', 'collapse', 'truncate', 'scroll'],
	},
	{
		id: 'display-message-alignment',
		tab: 'display',
		tabLabel: 'Display',
		label: 'User Message Alignment',
		description:
			'Position your messages on the left or right side of the chat; AI responses appear on the opposite side',
		keywords: [
			'alignment',
			'left',
			'right',
			'message',
			'chat',
			'position',
			'response',
			'ai response',
		],
	},
	{
		id: 'display-group-chat-auto-scroll',
		tab: 'display',
		tabLabel: 'Display',
		label: 'Group Chat Auto-Scroll',
		description: 'Automatically scroll group chats to the newest message when new messages arrive.',
		keywords: [
			'group chat',
			'auto-scroll',
			'autoscroll',
			'scroll',
			'follow',
			'bottom',
			'newest',
			'messages',
		],
	},
	{
		id: 'display-colorblind-mode',
		tab: 'display',
		tabLabel: 'Display',
		label: 'Color Blind Mode',
		description:
			"Swap red/green/yellow semantics for Wong's colorblind-safe palette across agent status dots, diff add/remove, git status, the activity graph, Usage Dashboard charts, and file extension badges.",
		keywords: [
			'colorblind',
			'color blind',
			'colour blind',
			'colourblind',
			'accessibility',
			'a11y',
			'protanopia',
			'deuteranopia',
			'tritanopia',
			'wong',
			'palette',
			'vision',
			'contrast',
			'red green',
		],
	},
	{
		id: 'display-bionify-reading-mode',
		tab: 'display',
		tabLabel: 'Display',
		label: 'Bionify Emphasis (Reading Mode)',
		description:
			'Apply Bionify-style emphasis (Soft, Default, or Strong intensity) to long-form readers like File Preview and Auto Run. Includes algorithm controls.',
		keywords: [
			'bionify',
			'bionic',
			'reading',
			'reading mode',
			'accessibility',
			'a11y',
			'emphasis',
			'bold',
			'fixation',
			'intensity',
			'algorithm',
			'soft',
			'strong',
			'default',
			'file preview',
			'auto run',
			'long-form',
			'speed reading',
		],
	},
	{
		id: 'display-icon-theme',
		tab: 'display',
		tabLabel: 'Display',
		label: 'Files Pane Icon Theme',
		description: 'Default or Rich (Material Icon Theme style) for the Files pane',
		keywords: ['icon', 'theme', 'files', 'material', 'rich', 'explorer'],
	},
	{
		id: 'display-window-chrome',
		tab: 'display',
		tabLabel: 'Display',
		label: 'Window Chrome',
		description:
			'Native or custom title bar and auto-hide menu bar (press Alt to reveal it temporarily)',
		keywords: [
			'title bar',
			'titlebar',
			'menu bar',
			'menubar',
			'native',
			'custom',
			'chrome',
			'window',
			'auto hide',
			'auto-hide',
			'alt',
			'frameless',
		],
	},
	{
		id: 'display-main-header-panel',
		tab: 'display',
		tabLabel: 'Display',
		label: 'Main Header Panel',
		description:
			'Toggle the agent name, session ID, and session cost pills shown in the main header',
		keywords: [
			'header',
			'main header',
			'panel',
			'agent name',
			'session name',
			'session id',
			'session uuid',
			'uuid',
			'cost',
			'pill',
			'pills',
			'badge',
			'top bar',
			'title bar',
		],
	},
	{
		id: 'display-left-panel-starred-sessions',
		tab: 'display',
		tabLabel: 'Display',
		label: 'Show Starred Sessions section',
		description:
			'Show a Starred Sessions section at the top of the left side bar listing every starred AI tab and named session across all agents',
		keywords: [
			'starred',
			'star',
			'favorite',
			'favourite',
			'bookmark',
			'pinned',
			'left',
			'side',
			'sidebar',
			'side bar',
			'side panel',
			'panel',
			'section',
			'tabs',
			'sessions',
			'agents',
			'jump',
			'navigate',
			'cross-agent',
		],
	},
	{
		id: 'display-left-side-panel',
		tab: 'display',
		tabLabel: 'Display',
		label: 'Left Side Panel',
		description:
			'Configure the left side bar: group member counts, collapsed pills per row, location pills, git change indicator, Cue indicator, worktree badges, and full vs abbreviated group labels on bookmarked agents',
		keywords: [
			'left',
			'side',
			'sidebar',
			'side bar',
			'side panel',
			'panel',
			'group',
			'groups',
			'count',
			'member',
			'members',
			'ungrouped',
			'agents',
			'remote',
			'local',
			'git',
			'pill',
			'pills',
			'per row',
			'row',
			'rows',
			'wrap',
			'density',
			'collapsed',
			'badge',
			'badges',
			'location',
			'change',
			'changes',
			'dirty',
			'cue',
			'indicator',
			'terminal',
			'startup',
			'startup command',
			'sticky',
			'persistent',
			'prompt',
			'worktree',
			'work tree',
			'branch',
			'branch name',
			'agent list',
			'session list',
			'bookmark',
			'bookmarks',
			'bookmarked',
			'full',
			'full name',
			'full label',
			'abbreviated',
			'abbreviation',
			'tag',
			'label',
			'hide',
			'hide group',
			'hide pill',
			'group pill',
		],
	},
	{
		id: 'display-modal-layout',
		tab: 'display',
		tabLabel: 'Display',
		label: 'Modal Layout',
		description: 'Reset saved modal sizes',
		keywords: ['modal', 'dialog', 'resize', 'size', 'reset', 'layout', 'window'],
	},
	{
		id: 'display-file-edit-preview',
		tab: 'display',
		tabLabel: 'Display',
		label: 'File Edit & Preview',
		description:
			'Line numbers, word wrap default, and per-button visibility for the file preview / editor toolbar',
		keywords: [
			'file',
			'edit',
			'editor',
			'preview',
			'line numbers',
			'gutter',
			'word wrap',
			'wrap',
			'soft wrap',
			'horizontal scroll',
			'toolbar',
			'buttons',
			'visibility',
			'deep link',
			'maestro://',
		],
	},
	{
		id: 'display-tab-filtering',
		tab: 'display',
		tabLabel: 'Display',
		label: 'Tab Options',
		description: `Show starred, file preview, terminal, and browser tabs when filtering by unread; ${META_KEY_NAME}+0 vs ${META_KEY_NAME}+9 last-tab shortcut; browser tab domain pill; scroll tabs with the mouse wheel`,
		keywords: [
			'tab',
			'filter',
			'unread',
			'starred',
			'file preview',
			'terminal tab',
			'browser tab',
			'cmd 0',
			'cmd 9',
			'command 0',
			'command 9',
			'ctrl 0',
			'ctrl 9',
			'last tab',
			'go to last tab',
			'shortcut',
			'keyboard',
			'browser style',
			'browser tab',
			'domain',
			'hostname',
			'url',
			'pill',
			'wheel',
			'mouse wheel',
			'scroll',
			'scroll tabs',
			'pan',
			'tab bar',
			'tab strip',
		],
	},
	{
		id: 'display-document-graph',
		tab: 'display',
		tabLabel: 'Display',
		label: 'Document Graph',
		description: 'External links and maximum nodes for the document graph',
		keywords: [
			'document',
			'graph',
			'nodes',
			'links',
			'external',
			'visualization',
			'mindmap',
			'force',
			'radial',
			'wiki',
			'backlinks',
		],
	},
	{
		id: 'display-context-warnings',
		tab: 'display',
		tabLabel: 'Display',
		label: 'Context Window Warnings',
		description: 'Show warning banners when context window usage reaches configurable thresholds',
		keywords: [
			'context',
			'window',
			'warning',
			'threshold',
			'yellow',
			'red',
			'consumption',
			'banner',
			'percent',
			'percentage',
			'usage',
			'compaction',
		],
	},
	{
		id: 'display-file-indexing',
		tab: 'display',
		tabLabel: 'Display',
		label: 'File Indexing & File Panel Settings',
		description:
			'Local ignore patterns, gitignore handling, max recursion depth, max file entries, and SSH cap reduction for the Files panel',
		keywords: [
			'ignore',
			'patterns',
			'glob',
			'exclude',
			'gitignore',
			'file indexing',
			'file explorer',
			'file panel',
			'files panel',
			'files pane',
			'panel',
			'pane',
			'depth',
			'recursion',
			'max entries',
			'max files',
			'limit',
			'memory',
			'load more',
			'load all',
			'scan',
			'indexer',
			'10k',
			'50k',
			'100k',
			'250k',
			'500k',
			'preset',
			'ssh',
			'remote',
			'reduce',
			'fraction',
			'percent',
			'percentage',
			'cap',
			'budget',
		],
	},
];
