import * as fs from 'node:fs/promises';
import * as crypto from 'node:crypto';
import { isAbsolute, join, resolve } from 'node:path';
import { tmpdir } from 'node:os';

/**
 * The only state OMP can discover at startup. It is generated by the host and
 * deliberately contains no plugin, hook, MCP, skill, rule, or tool input.
 */
export interface OmpRuntimeProfile {
	/** OMP's restricted profile identifier, never an absolute path. */
	readonly profile: string;
	readonly config: string;
	readonly sterileCwd: string;
	readonly env: Readonly<Record<string, string>>;
	readonly model: string;
}

export interface OmpRuntimeProfileStat {
	readonly isDirectory: () => boolean;
	readonly isFile: () => boolean;
	readonly isSymbolicLink: () => boolean;
	readonly mode: number;
	readonly uid?: number;
}

/** Narrow filesystem seam so launch-state validation is testable. */
export interface OmpRuntimeProfileFilesystem {
	readonly mkdtemp: (prefix: string) => Promise<string>;
	readonly mkdir: (path: string, options?: { recursive?: boolean; mode?: number }) => Promise<void>;
	readonly writeFile: (path: string, content: string, options?: { mode?: number }) => Promise<void>;
	readonly readFile: (path: string, encoding: 'utf8') => Promise<string>;
	readonly readdir: (path: string) => Promise<readonly string[]>;
	readonly lstat: (path: string) => Promise<OmpRuntimeProfileStat>;
	readonly realpath: (path: string) => Promise<string>;
}

export interface OmpRuntimeProfileServiceDependencies {
	/** App-controlled state is rooted here when persistence is required. */
	readonly stateRoot?: string;
	/** Pinned by the Maestro host; never obtained from child config or environment. */
	readonly model?: string;
	/** Only credential variables explicitly issued by the host may cross spawn. */
	readonly authEnvironment?: Readonly<Record<string, string>>;
	readonly filesystem?: OmpRuntimeProfileFilesystem;
}

const PROFILE_CONFIG = 'maestro-omp.yaml';
const OMP_VERSION_PROFILE_PREFIX = 'maestro-omp-16.4.8-';
const ENV_KEY = /^[A-Z][A-Z0-9_]{0,63}$/u;
const FORBIDDEN_AUTH_ENV: Readonly<Record<string, true>> = {
	PATH: true,
	HOME: true,
	USERPROFILE: true,
	OMP_PROFILE: true,
	PI_HOME: true,
};
const DEFAULT_MODEL = 'claude';

/**
 * Creates and validates a sterile process cwd and OMP profile before *every*
 * launch. A profile mutation is a hard failure rather than an opportunity to
 * rediscover configuration from an untrusted workspace or user home.
 */
export class OmpRuntimeProfileService {
	private state: OmpRuntimeProfile | undefined;
	private expectedConfig: string | undefined;
	private privateDirectories: readonly string[] = [];

	constructor(private readonly deps: OmpRuntimeProfileServiceDependencies = {}) {}

	async prepareForLaunch(): Promise<OmpRuntimeProfile> {
		if (!this.state) await this.create();
		const state = this.state;
		if (!state) throw new Error('OMP profile state is unavailable');
		await this.assertCurrent(state);
		return state;
	}

	private async create(): Promise<void> {
		const filesystem = this.filesystem;
		const base = this.deps.stateRoot
			? resolve(this.deps.stateRoot)
			: await filesystem.mkdtemp(join(tmpdir(), OMP_VERSION_PROFILE_PREFIX));
		if (!isAbsolute(base)) throw new Error('OMP profile state root must be absolute');
		if (this.deps.stateRoot) await filesystem.mkdir(base, { recursive: true, mode: 0o700 });

		const profileDirectory = join(base, 'profile');
		const sterileCwd = join(base, 'cwd');
		const home = join(base, 'home');
		const configHome = join(base, 'config');
		const appData = join(base, 'appdata');
		const localAppData = join(base, 'localappdata');
		const profile = `maestro-omp-${crypto.randomBytes(16).toString('hex')}`;
		const config = join(profileDirectory, PROFILE_CONFIG);
		for (const directory of [
			profileDirectory,
			sterileCwd,
			home,
			configHome,
			appData,
			localAppData,
		]) {
			await filesystem.mkdir(directory, { recursive: true, mode: 0o700 });
		}
		const model = this.deps.model ?? DEFAULT_MODEL;
		if (!isSafeModel(model)) throw new Error('OMP model is not host-approved');
		this.expectedConfig = configFor(model);
		await filesystem.writeFile(config, this.expectedConfig, { mode: 0o600 });

		this.privateDirectories = [
			profileDirectory,
			sterileCwd,
			home,
			configHome,
			appData,
			localAppData,
		];
		const env = buildEnvironment(
			profile,
			home,
			configHome,
			appData,
			localAppData,
			this.deps.authEnvironment
		);
		this.state = Object.freeze({ profile, config, sterileCwd, env, model });
	}

	private async assertCurrent(profile: OmpRuntimeProfile): Promise<void> {
		if (!this.expectedConfig) throw new Error('OMP profile state is unavailable');
		const profileDirectory = this.privateDirectories[0];
		if (!profileDirectory || this.privateDirectories.length !== 6) {
			throw new Error('OMP profile state is unavailable');
		}
		await Promise.all(this.privateDirectories.map((directory) => this.assertDirectory(directory)));
		await this.assertFile(profile.config);
		const [entries, cwdEntries] = await Promise.all([
			this.filesystem.readdir(profileDirectory),
			this.filesystem.readdir(profile.sterileCwd),
		]);
		if (
			entries.length !== 1 ||
			entries[0] !== PROFILE_CONFIG ||
			cwdEntries.length !== 0 ||
			(await this.filesystem.readFile(profile.config, 'utf8')) !== this.expectedConfig
		) {
			throw new Error('OMP profile contains unapproved discovery state');
		}
	}

	private async assertDirectory(value: string): Promise<void> {
		const [entry, canonical] = await Promise.all([
			this.filesystem.lstat(value),
			this.filesystem.realpath(value),
		]);
		if (
			!entry.isDirectory() ||
			entry.isSymbolicLink() ||
			!samePath(canonical, value) ||
			!isOwnerOnly(entry)
		) {
			throw new Error('OMP profile path is unsafe');
		}
	}

	private async assertFile(value: string): Promise<void> {
		const [entry, canonical] = await Promise.all([
			this.filesystem.lstat(value),
			this.filesystem.realpath(value),
		]);
		if (
			!entry.isFile() ||
			entry.isSymbolicLink() ||
			!samePath(canonical, value) ||
			!isOwnerOnly(entry)
		) {
			throw new Error('OMP profile path is unsafe');
		}
	}

	private get filesystem(): OmpRuntimeProfileFilesystem {
		return this.deps.filesystem ?? nodeFilesystem;
	}
}

function configFor(model: string): string {
	return (
		[
			'# Generated by Maestro. Any change invalidates this launch profile.',
			`model: ${JSON.stringify(model)}`,
			'disabledProviders:',
			'  - native',
			'  - claude',
			'  - claude-plugins',
			'  - codex',
			'  - gemini',
			'  - opencode',
			'  - cursor',
			'  - windsurf',
			'  - cline',
			'  - github',
			'  - mcp-json',
			'  - omp-plugins',
			'  - agents',
			'  - agents-md',
			'  - vscode',
			'extensions: []',
			'disabledExtensions: ["*"]',
			'enabledModels: []',
			'mcp:',
			'  enabled: false',
			'  enableProjectConfig: false',
			'  discoveryMode: off',
			'  notifications: false',
			'skills:',
			'  enabled: false',
			'  enableSkillCommands: false',
			'bash:',
			'  enabled: false',
			'web_search:',
			'  enabled: false',
			'browser:',
			'  enabled: false',
			'tools:',
			'  approvalMode: always-ask',
			'  discoveryMode: off',
			'startup:',
			'  checkUpdate: false',
		].join('\n') + '\n'
	);
}

function buildEnvironment(
	profile: string,
	home: string,
	configHome: string,
	appData: string,
	localAppData: string,
	authEnvironment: Readonly<Record<string, string>> | undefined
): Readonly<Record<string, string>> {
	const environment: Record<string, string> = {
		OMP_PROFILE: profile,
		HOME: home,
		USERPROFILE: home,
		XDG_CONFIG_HOME: configHome,
		APPDATA: appData,
		LOCALAPPDATA: localAppData,
		PI_NO_PTY: '1',
		PI_NO_TITLE: '1',
		PI_NOTIFICATIONS: 'off',
	};
	for (const [key, value] of Object.entries(authEnvironment ?? {})) {
		if (
			!ENV_KEY.test(key) ||
			FORBIDDEN_AUTH_ENV[key] ||
			typeof value !== 'string' ||
			value.length > 16_384
		) {
			throw new Error('OMP auth environment is not allowlisted');
		}
		environment[key] = value;
	}
	return Object.freeze(environment);
}

function isSafeModel(value: string): boolean {
	return /^[A-Za-z0-9][A-Za-z0-9._/-]{0,127}$/u.test(value);
}

function isOwnerOnly(entry: OmpRuntimeProfileStat): boolean {
	// Windows does not expose POSIX permission/uid bits through Node's lstat.
	// Reparse checks remain mandatory there; ownership is enforced by the
	// app-controlled state-root ACL.
	if (process.platform === 'win32') return true;
	if ((entry.mode & 0o022) !== 0) return false;
	const uid = process.getuid?.();
	return uid === undefined || entry.uid === undefined || uid === entry.uid;
}

function samePath(left: string, right: string): boolean {
	return process.platform === 'win32'
		? left.toLocaleLowerCase() === right.toLocaleLowerCase()
		: left === right;
}

const nodeFilesystem: OmpRuntimeProfileFilesystem = {
	mkdtemp: fs.mkdtemp,
	mkdir: async (path, options) => {
		await fs.mkdir(path, options);
	},
	writeFile: fs.writeFile,
	readFile: fs.readFile,
	readdir: fs.readdir,
	lstat: fs.lstat,
	realpath: fs.realpath,
};
