import { THEMES } from '../../shared/themes';
import { discoveryPanel } from './discovery/ui';

// The native connection shell uses the same default palette as full Maestro.
const colors = THEMES.dracula.colors;
// index.ts places the remote view at y=72, so the header must stay exactly 72px tall.
export const connectionPage = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'"><title>Maestro Lite</title><style>
:root{color-scheme:dark;--muted:color-mix(in srgb,${colors.textMain} 70%,${colors.bgMain})}*{box-sizing:border-box}body{margin:0;background:${colors.bgMain};color:${colors.textMain};font:14px/1.5 system-ui,sans-serif}
header{height:72px;overflow:hidden;display:flex;gap:8px;align-items:center;padding:0 20px;border-bottom:1px solid ${colors.border};background:${colors.bgSidebar}}header strong{white-space:nowrap}header button{flex:none;white-space:nowrap}#status{flex:1;min-width:0;font-size:12px;color:var(--muted);overflow:hidden;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical}
button,input,select,textarea,summary{font:inherit;color:inherit}button,input,select,textarea{border:1px solid ${colors.border};border-radius:6px;background:${colors.bgActivity}}button{min-height:34px;padding:6px 14px;cursor:pointer}summary{cursor:pointer}button:hover:not(:disabled){border-color:${colors.accent}}button:disabled{opacity:.55;cursor:default}
.primary{background:${colors.accent};border-color:${colors.accent};color:${colors.accentForeground};font-weight:600}
:focus-visible{outline:2px solid ${colors.accent};outline-offset:2px}h1:focus,h2:focus{outline:none}
main{max-width:680px;margin:0 auto;padding:28px 24px 48px}h1{font-size:22px;margin:0}h2{font-size:16px;margin:0}.lede{margin:4px 0 20px;color:var(--muted)}p{margin:6px 0}
label{display:block;margin:12px 0 4px;font-weight:500}input:not([type=checkbox]),select,textarea{display:block;width:100%;padding:8px 10px;margin-top:4px}textarea{min-height:80px;font:12px ui-monospace,monospace}
.check{display:flex;gap:10px;align-items:flex-start;font-weight:400}.check input{flex:none;width:16px;height:16px;margin:3px 0 0;accent-color:${colors.accent}}
.row{display:flex;gap:10px;align-items:end}.row>*{flex:1}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.inline-field{display:flex;gap:8px;align-items:stretch}.inline-field input{margin-top:0}.inline-field button{flex:none}
.hint{font-size:13px;color:var(--muted)}.field-error{color:${colors.error}}.field-error:empty{display:none}
#error{margin:0 0 16px;padding:10px 12px;border:1px solid ${colors.error};border-radius:6px;background:color-mix(in srgb,${colors.error} 14%,${colors.bgMain});white-space:pre-wrap;overflow-wrap:anywhere}#error:empty{display:none}#error-actions{margin:-8px 0 16px}#notice:empty{display:none}
.task{margin-bottom:24px;padding:20px;border:1px solid ${colors.accent};border-radius:10px;background:${colors.bgSidebar};overflow-wrap:anywhere}.task.quiet{padding:12px 16px;border-color:${colors.border};background:none}.task.quiet h2{font-size:14px}.task.quiet .actions{margin-top:8px}
#pair-pin{max-width:12ch;font:600 26px/1.2 ui-monospace,"Cascadia Mono",Consolas,monospace;letter-spacing:.2em;text-align:center}
.section-head{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:8px}
.host-cards{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:10px;margin:12px 0}.host-card{display:flex;flex-direction:column;align-items:flex-start;gap:2px;padding:12px 14px;text-align:left;white-space:normal;overflow-wrap:anywhere}.host-card:disabled{opacity:.75}.host-card strong{font-size:15px}.host-card [data-availability=ready]{color:${colors.success}}
details{padding:12px 0;border-top:1px solid ${colors.border}}#discovery-panel details:first-of-type{margin-top:16px}details[open]>summary{margin-bottom:8px}#discovery-sources{padding-left:20px;margin:0 0 10px}li{margin:4px 0}
.panel{margin-top:12px;padding:16px;border:1px solid ${colors.border};border-radius:8px}#manual-connections{margin-top:8px}#manual-new{margin-top:4px}
#commands{display:none}#commands.open{display:block;padding:12px;border:1px solid ${colors.border};border-radius:8px;background:${colors.bgSidebar};position:absolute;right:20px;top:64px;z-index:2;min-width:240px}#commands button{display:flex;justify-content:space-between;gap:16px;margin:6px 0;width:100%}#commands kbd{font:12px ui-monospace,monospace;color:var(--muted)}
#identity{overflow-wrap:anywhere}[hidden]{display:none!important}
@media(max-width:1000px){header{padding:0 10px;gap:4px}header button{padding:4px 8px;font-size:12px}#status{font-size:11px}}@media(max-width:650px){main{padding:16px}.row,.inline-field{display:block}.inline-field button{margin-top:8px}.task{padding:16px}}
.task{border:0;background:none;padding:24px 0;min-height:280px}.task h2,h2{font-size:24px;line-height:1.3}.host-cards{grid-template-columns:1fr}.host-card{width:100%}#discovery-panel{min-height:300px;padding:24px 0}#flow-progress{margin:0 0 16px}#guide-options,.alternative-actions{margin-top:24px;padding-top:16px;border-top:1px solid ${colors.border}}#guide-options button{background:none;border:0;padding-left:0}.alternative-actions{display:flex;flex-direction:column;align-items:flex-start;gap:10px}#guide-back{margin-bottom:20px}#pair-pin{font-size:32px}
</style></head><body>
<header><strong>Maestro Lite</strong><span id="status" role="status" aria-live="polite">Not connected</span><button id="connections" title="Connections (Ctrl/Cmd+Shift+L)">Connections</button><button id="return" hidden>Return to Maestro</button><button id="reconnect" disabled>Reconnect</button><button id="disconnect" disabled>Disconnect</button><button id="palette" title="Connection commands (Ctrl/Cmd+Shift+P)" aria-expanded="false" aria-controls="commands">Commands</button><button id="close">Close Lite</button></header>
<div id="commands" role="group" aria-label="Connection commands"><button data-action="connections">Connections <kbd>Ctrl/Cmd+Shift+L</kbd></button><button data-action="discover">Find hosts <kbd>Ctrl/Cmd+Shift+D</kbd></button><button data-action="reconnect">Reconnect <kbd>Ctrl/Cmd+Shift+R</kbd></button><button data-action="disconnect">Disconnect</button><button data-action="dismiss">Back <kbd>Esc</kbd></button></div>
<main id="picker">
<p id="error" role="alert" tabindex="-1"></p><div id="error-actions" hidden><button id="error-forget" type="button">Forget pairing</button></div><p id="notice" role="status" aria-live="polite"></p>
${discoveryPanel}
<section id="manual-connections" hidden><h2 id="manual-heading" tabindex="-1">Use a link or SSH</h2><button id="manual-new" type="button">Add a connection</button>
<section id="saved" class="panel" aria-labelledby="saved-heading" hidden><h2 id="saved-heading">Saved connections</h2><label for="profiles">Connection</label><select id="profiles"></select><div class="actions"><button id="connect" class="primary">Connect</button><button id="edit">Edit</button><button id="new">Add connection</button><button id="remove">Delete</button></div><details id="identity-details" hidden><summary>Host identity</summary><p id="identity" class="hint"></p><button id="trust" hidden>Forget host identity and sign in again</button></details></section>
<form id="profile" class="panel" aria-labelledby="form-title"><h2 id="form-title">Add a connection</h2><label for="name">Name</label><input id="name" required maxlength="100" placeholder="Work computer" autocomplete="off"><label for="transport">Connection type</label><select id="transport"><option value="https">HTTPS link (sign in after connecting)</option><option value="ssh">SSH tunnel (SSH must already work)</option></select><label for="url">Remote Control link</label><input id="url" type="url" required placeholder="https://your-host.example/your-link/desktop" autocomplete="off" spellcheck="false" aria-describedby="url-help"><p id="url-help" class="hint">In Maestro on the host, open Remote Control and copy its link. You'll sign in after connecting.</p>
<section id="ssh" hidden><label for="host">SSH host or alias</label><input id="host" list="aliases" placeholder="From your SSH config or the host owner" aria-describedby="ssh-help"><datalist id="aliases"></datalist><p id="ssh-help" class="hint">SSH must already work from this computer, with a verified host key. Lite uses your SSH key or agent and never asks for a password.</p><details id="advanced"><summary>Advanced SSH settings</summary><div class="row"><div><label for="username">Username (optional)</label><input id="username"></div><div><label for="port">SSH port</label><input id="port" type="number" min="1" max="65535" value="22"></div></div><label for="key">Private key path (optional)</label><input id="key" placeholder="Leave blank to use your SSH setup"><label class="check"><input id="config" type="checkbox"><span>Use a saved SSH config alias</span></label><label for="options">Extra SSH options (JSON)</label><textarea id="options" spellcheck="false" aria-describedby="options-help">{}</textarea><p id="options-help" class="hint">Change these only if the host owner gave you different settings. A saved alias keeps its configured port.</p></details></section>
<div class="actions"><button id="save-connect" type="submit" class="primary">Save and connect</button><button id="save" type="submit">Save</button><button type="button" id="cancel">Cancel</button></div></form>
</section></main></body></html>`;
