import { THEMES } from '../../shared/themes';

// The native connection shell uses the same default palette as full Maestro.
const colors = THEMES.dracula.colors;
export const connectionPage = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'"><title>Maestro Lite</title><style>
:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:${colors.bgMain};color:${colors.textMain};font:14px system-ui;line-height:1.5}header{height:72px;display:flex;gap:8px;align-items:center;padding:12px 20px;border-bottom:1px solid ${colors.border};background:${colors.bgSidebar}}strong{white-space:nowrap}#status{flex:1;min-width:0;font-size:12px;overflow:hidden;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical}button,input,select,textarea,summary{font:inherit;border-radius:6px}button,input,select,textarea{border:1px solid ${colors.border};padding:9px 12px;background:${colors.bgActivity};color:inherit}button,summary{cursor:pointer}button:hover{border-color:${colors.accent}}button:disabled{opacity:.5;cursor:default}.primary{background:${colors.accent};color:${colors.accentForeground};font-weight:600}button:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible,summary:focus-visible{outline:2px solid ${colors.accent};outline-offset:3px}main{padding:24px;max-width:760px;margin:auto}h1{font-size:24px;margin:0 0 8px}h2{font-size:18px;margin:0 0 12px}p{margin:8px 0 16px}label{display:block;margin:12px 0 4px;font-weight:500}input,select,textarea{display:block;width:100%;margin-top:5px}textarea{min-height:80px}.row{display:flex;gap:10px;align-items:end}.row>*{flex:1}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:18px}.hint{font-size:12px;opacity:.85;margin:6px 0 12px}.panel{padding:20px;border:1px solid ${colors.border};border-radius:8px;background:${colors.bgSidebar};margin-top:20px}details{margin:16px 0}summary{padding:8px 0;font-weight:600}li{margin:8px 0}#error{color:${colors.error};white-space:pre-wrap;overflow-wrap:anywhere}#error:empty{display:none}#commands{display:none}#commands.open{display:block;padding:16px;border:1px solid ${colors.border};background:${colors.bgSidebar};position:absolute;right:20px;top:64px;z-index:2}#commands button{display:block;margin:8px 0;width:100%}[hidden]{display:none!important}#identity{overflow-wrap:anywhere}#config{display:inline;width:auto;margin-right:6px}@media(max-width:650px){main{padding:16px}.row{display:block}header{padding:8px;gap:4px}header button{padding:6px;font-size:11px}header strong{font-size:12px}#status{font-size:11px}.panel{padding:16px}}
</style></head><body>
<header><strong>Maestro Lite</strong><span id="status" role="status" aria-live="polite">Not connected</span><button id="connections" title="Connections (Ctrl/Cmd+Shift+L)">Connections</button><button id="return" hidden>Return to Maestro</button><button id="reconnect" disabled>Reconnect</button><button id="disconnect" disabled>Disconnect</button><button id="palette" title="Connection commands (Ctrl/Cmd+Shift+P)" aria-expanded="false" aria-controls="commands">Commands</button><button id="close">Close Lite</button></header>
<div id="commands" role="group" aria-label="Connection commands"><button data-action="connections">Connections</button><button data-action="reconnect">Reconnect</button><button data-action="disconnect">Disconnect</button><button data-action="dismiss">Back - Esc</button></div>
<main id="picker"><h1>Your Maestro, on another computer</h1><p>Connect to the computer running full Maestro. Your agents, files, and tools stay on that computer. Keep it awake and Maestro open while you work here.</p>
<details id="setup-help"><summary>First time? Set up the host computer</summary><ol><li>Open full Maestro on the computer where your agents and project files live. This is your <strong>host</strong>.</li><li>Open <strong>Remote Control</strong> in full Maestro and enable it. Copy its Remote Control link, or ask the person managing that computer for the link and connection details.</li><li>Choose the connection method that matches the link below. For HTTPS, sign in using the host's login when prompted. For SSH, ask the host owner to help set up SSH access first.</li></ol><p class="hint">A link starting with 127.0.0.1 or localhost refers to the host computer when used through SSH. It is not a public internet address. Keep your Remote Control link private.</p></details>
<section id="saved" class="panel" hidden><h2>Saved connections</h2><label for="profiles">Host computer</label><select id="profiles"></select><div class="actions"><button id="connect" class="primary">Connect</button><button id="edit">Edit connection</button><button id="new">Add connection</button><button id="remove">Delete connection</button></div><p class="hint">After connecting, choose an agent in the Left Bar, type a message, and send it. If the list is empty, choose Create your first agent and select a project folder on the host.</p></section>
<form id="profile" class="panel"><h2 id="form-title">Add your first connection</h2><label for="name">Connection name</label><input id="name" required maxlength="100" placeholder="For example, My work computer" autocomplete="off"><label for="transport">How will you connect?</label><select id="transport"><option value="https">HTTPS link (sign in when prompted)</option><option value="ssh">SSH tunnel (requires SSH setup)</option></select><label for="url">Remote Control link</label><input id="url" type="url" required placeholder="https://your-host.example/your-link/desktop" autocomplete="off" spellcheck="false" aria-describedby="url-help"><p id="url-help" class="hint">Paste the complete HTTPS link from the host. You will sign in after connecting.</p>
<section id="ssh" hidden><label for="host">SSH host or saved alias</label><input id="host" list="aliases" placeholder="Provided by the host owner" aria-describedby="ssh-help"><datalist id="aliases"></datalist><p id="ssh-help" class="hint">SSH must already work from this computer, including a verified host key. Lite uses your existing SSH key or agent; it does not ask for an SSH password.</p><details id="advanced"><summary>Advanced SSH settings</summary><div class="row"><div><label for="username">Username (optional)</label><input id="username"></div><div><label for="port">SSH port</label><input id="port" type="number" min="1" max="65535" value="22"></div></div><label for="key">Private key path (optional)</label><input id="key" placeholder="Leave blank to use your SSH setup"><label><input id="config" type="checkbox">Use a saved SSH config alias</label><label for="options">Extra SSH options (JSON)</label><textarea id="options" spellcheck="false" aria-describedby="options-help">{}</textarea><p id="options-help" class="hint">Leave these defaults unless the host owner supplied different settings. A saved alias preserves its configured port.</p></details></section>
<div class="actions"><button id="save-connect" type="submit" class="primary">Save and connect</button><button id="save" type="submit">Save for later</button><button type="button" id="cancel">Cancel</button></div></form>
<p id="notice" role="status" aria-live="polite"></p><p id="error" role="alert" tabindex="-1"></p><details id="identity-details" hidden><summary>Host identity</summary><p id="identity" class="hint"></p><button id="trust" hidden>Forget previous host identity and authenticate again</button></details></main></body></html>`;
