import { THEMES } from '../../../shared/themes';
const colors = THEMES.dracula.colors;
export const hostPairingPage = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src data:"><title>Connect another device</title><style>
:root{color-scheme:dark;--muted:color-mix(in srgb,${colors.textMain} 70%,${colors.bgMain})}*{box-sizing:border-box}body{margin:0;background:${colors.bgMain};color:${colors.textMain};font:14px/1.5 system-ui,sans-serif}main{max-width:640px;margin:0 auto;padding:16px 24px 40px}
header{display:flex;align-items:center;justify-content:space-between;gap:12px;padding-bottom:12px;border-bottom:1px solid ${colors.border}}h1{font-size:18px;margin:0}h2{font-size:15px;margin:0}h3{font-size:17px;margin:0 0 4px}p{margin:6px 0}ol{margin:8px 0;padding-left:20px}li{margin:4px 0}
section{padding:18px 0;border-bottom:1px solid ${colors.border}}details{padding:14px 0;border-bottom:1px solid ${colors.border}}summary{cursor:pointer;font-weight:600}details[open]>summary{margin-bottom:8px}
button,input,select,textarea{font:inherit;color:inherit}button{min-height:34px;padding:6px 14px;border:1px solid ${colors.border};border-radius:6px;background:${colors.bgActivity};cursor:pointer}button:hover:not(:disabled){border-color:${colors.accent}}button:disabled{opacity:.55;cursor:default}
.primary{background:${colors.accent};border-color:${colors.accent};color:${colors.accentForeground};font-weight:600}.danger{border-color:${colors.error};color:${colors.error}}:focus-visible{outline:2px solid ${colors.accent};outline-offset:2px}h2:focus,h3:focus{outline:none}
input:not([type=checkbox]),select,textarea{display:block;width:100%;margin-top:4px;padding:8px 10px;background:${colors.bgActivity};border:1px solid ${colors.border};border-radius:6px}textarea{resize:vertical;font:12px ui-monospace,monospace}label{display:block;margin-top:12px}
.check{display:flex;gap:10px;align-items:flex-start}.check input{flex:none;width:16px;height:16px;margin:3px 0 0;accent-color:${colors.accent}}.actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px}.row{display:flex;align-items:center;gap:10px}.muted{color:var(--muted)}.field-error{color:${colors.error}}
.badge{font-size:12px;padding:0 8px;border:1px solid ${colors.border};border-radius:999px;color:var(--muted)}.badge[data-tone=on]{color:${colors.success};border-color:currentColor}.badge[data-tone=warn]{color:${colors.warning};border-color:currentColor}.badge:empty{display:none}
#error{margin-top:12px;padding:10px 12px;border:1px solid ${colors.error};border-radius:6px;background:color-mix(in srgb,${colors.error} 14%,${colors.bgMain});white-space:pre-wrap;overflow-wrap:anywhere}#error:empty{display:none}
.request{margin-top:16px;padding:20px;border:1px solid ${colors.accent};border-radius:10px;background:${colors.bgSidebar};overflow-wrap:anywhere}.request.final{border-color:${colors.warning}}.request .actions{margin-top:16px}
.code{margin:18px 0 4px;text-align:center;font:600 44px/1.15 ui-monospace,"Cascadia Mono",Consolas,monospace;letter-spacing:.14em;white-space:nowrap}.code span+span{margin-left:.45em}.expiry{text-align:center}
.risk{margin:12px 0;padding:12px 14px;border-left:3px solid ${colors.warning};border-radius:4px;background:${colors.bgActivity}}
.devices{list-style:none;margin:8px 0 0;padding:0}.devices li{display:flex;flex-wrap:wrap;align-items:center;justify-content:space-between;gap:8px;padding:10px 0;border-top:1px solid ${colors.border};overflow-wrap:anywhere}.devices li:first-child{border-top:0}.devices .actions{margin-top:0}
kbd{margin-left:6px;padding:0 4px;border:1px solid ${colors.border};border-radius:4px;font:12px ui-monospace,monospace;color:var(--muted)}img{display:block;width:100%;max-width:240px;margin-top:8px;background:#fff}
.sr-only{position:absolute;width:1px;height:1px;margin:-1px;padding:0;overflow:hidden;clip:rect(0 0 0 0);white-space:nowrap;border:0}[hidden]{display:none!important}
@media(max-width:480px){main{padding:14px 14px}.code{font-size:34px}.actions>*{flex:1 1 auto}}
.guide{min-height:280px;padding:32px 0}.guide h2,.request h3{font-size:24px;line-height:1.3}.request{border:0;background:none;padding:16px 0;margin:0}.code{font-size:48px}#flow-progress{margin:24px 0 0;font-size:13px}footer{padding-top:20px;border-top:1px solid ${colors.border}}footer button{background:none;border:0;padding-left:0}header h1{flex:1}
</style></head><body><main>
<header><button id="back" type="button" hidden>Back</button><h1 id="page-title">Connect another device</h1><button id="close" type="button" aria-keyshortcuts="Escape">Close <kbd aria-hidden="true">Esc</kbd></button></header>
<p id="error" role="alert" tabindex="-1"></p><p id="announcer" class="sr-only" role="status" aria-live="polite"></p>
<p id="flow-progress" class="muted">Getting ready</p>
<section id="requests-section" aria-label="Current pairing request" hidden><div id="requests"></div><button id="next-request" type="button" hidden>Next request</button></section>
<section id="waiting-step" class="guide" aria-labelledby="waiting-heading" hidden><h2 id="waiting-heading" tabindex="-1">Open Lite on your other computer</h2><p>Choose <strong id="how-to-name">this computer</strong> to send a connection request.</p><p class="muted">The request will appear here. Keep Maestro running.</p><p role="status">Waiting for your other computer…</p></section>
<section id="direct-panel" class="guide" aria-labelledby="access-heading"><h2 id="access-heading" tabindex="-1">Make this computer available</h2><p id="status" role="status">Checking Tailscale on this computer…</p><p id="direct-status" class="muted" hidden></p><div id="direct-setup" hidden><label class="check" id="direct-consent-label"><input id="direct-consent" type="checkbox" aria-describedby="direct-consent-error"><span>Devices I approve can use my chats, run agents and terminals, and read and change files on this computer until I remove them.</span></label><p id="direct-consent-error" class="field-error" hidden>Select the box to turn on access.</p></div><div class="actions"><button id="enable-direct" type="button" class="primary" hidden>Turn on access and continue</button><button id="open-tailscale" type="button" hidden>Open Tailscale</button><button id="refresh" type="button" hidden>Check again</button></div></section>
<section id="manage-page" hidden><h2 id="manage-heading" tabindex="-1">Manage access</h2><div class="row"><span>Access over Tailscale</span><span id="access-badge" class="badge"></span></div><p id="direct-hint" class="muted">Closing this window keeps access on. Turning it off disconnects devices.</p><button id="disable-direct" type="button" hidden>Turn off access</button><section id="devices-section" aria-labelledby="devices-heading"><h3 id="devices-heading" tabindex="-1">Paired devices</h3><p id="no-devices" class="muted">No paired devices yet.</p><ul id="paired-devices" class="devices"></ul></section><div class="actions"><button id="open-https" type="button">Use an HTTPS connection</button><button id="open-updates" type="button">Maestro updates</button></div></section>
<section id="attended-options" hidden><h2 id="https-heading" tabindex="-1">Connect over HTTPS</h2><p>Use an HTTPS address this computer already has.</p><span id="https-badge" class="muted"></span><p id="https-blocked" class="muted" hidden>Turn off Tailscale access in Manage access first to use HTTPS instead.</p>
<div id="https-on" hidden><p id="sharing-expiry"></p><div class="actions"><button id="invite" type="button" disabled>Create invitation</button><button id="stop" type="button">Stop HTTPS access</button></div></div>
<div id="invitation-panel" hidden><label for="invitation">Invitation for Maestro Lite</label><p id="invitation-expiry" class="muted"></p><textarea id="invitation" readonly rows="3" aria-describedby="invitation-expiry"></textarea><img id="invitation-qr" alt="QR code for the invitation"><div class="actions"><button id="copy-invitation" type="button">Copy invitation</button></div><p class="muted">Paste this invitation in Lite on the other computer. Pairing still requires a code and your approval.</p></div>
<form id="enable"><label>Name shown on other devices<input id="name" maxlength="64" autocomplete="off"></label><label>HTTPS address<select id="endpoint"></select></label><label class="check"><input id="advanced" type="checkbox"><span>Enter a different HTTPS address</span></label><input id="advanced-endpoint" type="url" placeholder="https://maestro.example.com" aria-label="Different HTTPS address" hidden>
<label class="check"><input id="lan" type="checkbox"><span>Also announce this computer on the local network</span></label><label id="interface-label" hidden>Local network<select id="interface" aria-describedby="interface-help"></select><span id="interface-help" class="muted">Uses multicast DNS on UDP port 5353.</span></label>
<label class="check"><input id="consent" type="checkbox" required><span>Devices I approve can use my chats, run agents and terminals, and read and change files until I remove them. HTTPS access stops after 8 hours or when I close this window.</span></label><div class="actions"><button id="enable-https" class="primary" type="submit">Turn on HTTPS access</button></div></form></section>
<section id="updates" hidden><h2 id="updates-heading" tabindex="-1">Maestro updates</h2><p id="update-status" class="muted">Check here if the other computer reports a different Maestro version. Nothing installs without your confirmation.</p><div class="actions"><button id="update-check" type="button">Check for updates</button><button id="update-download" type="button" hidden>Download update</button><button id="update-install" type="button" hidden>Restart and install</button></div></section>
<footer><button id="manage-access" type="button">Manage access</button></footer>
</main></body></html>`;
