import * as fs from 'fs';
import * as path from 'path';
import yaml from 'js-yaml';
import { writeCueYamlAtomicSync } from '../../main/cue/cue-yaml-write';
import { MaestroClient } from '../services/maestro-client';
import { readAgentRuns } from '../services/agent-run-store';
import { pianolaTaskAgentRunId } from '../../shared/agent-run';
import { generateUUID } from '../../shared/uuid';
import { getConfigDirectory, readSshRemotes } from '../services/storage';
import { ensurePianolaEnabled } from './pianola';
import {
	readPianolaPrograms,
	upsertPianolaProgram,
	readPianolaAsks,
	writePianolaAsks,
	readPianolaPlans,
	readPianolaDecisions,
	readPianolaSupervisorTargets,
	readPianolaProgramLoopMemo,
} from '../services/pianola-store';
import {
	validatePianolaProgram,
	dedupeAsk,
	briefRunsForPlans,
	derivePianolaBrief,
	type PianolaProgram,
	type PianolaAsk,
	type PianolaAskSeverity,
} from '../../shared/pianola/pianola-programs';

const print = (value: unknown, json?: boolean): void => {
	console.log(
		json
			? JSON.stringify(value)
			: typeof value === 'string'
				? value
				: JSON.stringify(value, null, 2)
	);
};
const fail = (message: string, json?: boolean): never => {
	if (json) console.log(JSON.stringify({ success: false, error: message }));
	else console.error(message);
	process.exit(1);
};
const GENERATED_BEGIN = '# generated by pianola program apply: begin';
const GENERATED_END = '# generated by pianola program apply: end';

type CueSubscription = Record<string, unknown>;

function generatedCueSubscriptions(
	program: PianolaProgram
): { pipeline: string; subscription: CueSubscription }[] {
	const role = (name: string) => program.roles[name];
	if (program.id === 'portfolio') {
		return (
			[
				[
					'cto',
					'10:00',
					'mon',
					'Write a technical review across products from pianola brief --json to ' +
						program.root +
						'/docs/reviews/cto-<date>.md. Do not publish.',
				],
				[
					'cmo',
					'11:00',
					'mon',
					'Write a growth review across products from pianola brief --json to ' +
						program.root +
						'/docs/reviews/cmo-<date>.md. Do not publish.',
				],
				[
					'social',
					'14:00',
					'wed',
					'Sweep each product docs/marketing/drafts and write a launch-copy review to ' +
						program.root +
						'/docs/reviews/social-<date>.md. Drafts only; do not publish.',
				],
			] as const
		)
			.filter(([key]) => !!role(key)?.agentId)
			.map(([key, time, day, prompt]) => ({
				pipeline: 'Portfolio weekly (color: #f59e0b)',
				subscription: {
					name: 'portfolio-weekly-' + key,
					event: 'time.scheduled',
					schedule_times: [time],
					schedule_days: [day],
					agent_id: role(key).agentId,
					pipeline_name: 'Portfolio weekly',
					label: 'Portfolio weekly ' + key,
					prompt,
				},
			}));
	}
	const entries: { pipeline: string; subscription: CueSubscription }[] = [];
	if (role('lead')?.agentId)
		entries.push({
			pipeline: program.title + ' standup (color: #06b6d4)',
			subscription: {
				name: program.id + '-standup',
				event: 'time.scheduled',
				schedule_times: ['08:30'],
				schedule_days: ['mon', 'tue', 'wed', 'thu', 'fri'],
				agent_id: role('lead').agentId,
				pipeline_name: program.title + ' standup',
				label: program.title + ' standup',
				prompt:
					'Read pianola brief --json for program ' +
					program.id +
					' and post a 5-line standup in this chat. Do not dispatch agents.',
			},
		});
	// A scheduled sweep rather than an agent.completed chain: Cue needs every pipeline to
	// start from a trigger line it owns, and a daily pass over the brief's verified work is
	// the same dated-artifact handoff Maestro's own marketing pipeline uses.
	if (role('marketing')?.agentId)
		entries.push({
			pipeline: program.title + ' marketing (color: #a855f7)',
			subscription: {
				name: program.id + '-marketing',
				event: 'time.scheduled',
				schedule_times: ['17:00'],
				schedule_days: ['mon', 'tue', 'wed', 'thu', 'fri'],
				agent_id: role('marketing').agentId,
				pipeline_name: program.title + ' marketing',
				label: program.title + ' marketing draft',
				prompt:
					'Read pianola brief --json for program ' +
					program.id +
					'. For each verified task from the last day that changes what a user sees, draft launch copy under ' +
					program.root +
					'/docs/marketing/drafts/<date>-<slug>.md. Drafts only; do not publish.',
			},
		});
	return entries;
}

export function updateGeneratedCueYaml(raw: string, program: PianolaProgram): string {
	const generated = generatedCueSubscriptions(program);
	const block =
		[
			GENERATED_BEGIN,
			...generated.flatMap(({ pipeline, subscription }) => [
				'  # Pipeline: ' + pipeline,
				...yaml
					.dump([subscription], { lineWidth: -1, noRefs: true })
					.trimEnd()
					.split('\n')
					.map((line) => '  ' + line),
			]),
			GENERATED_END,
		].join('\n') + '\n';
	const start = raw.indexOf(GENERATED_BEGIN);
	const end = raw.indexOf(GENERATED_END);
	if (start >= 0 || end >= 0) {
		if (start < 0 || end < start) throw new Error('Unmatched generated Cue block marker');
		const replacement = generated.length ? block : '';
		const updated =
			raw.slice(0, start) +
			replacement +
			raw.slice(end + GENERATED_END.length).replace(/^\r?\n/, '');
		if (
			!generated.length &&
			(yaml.load(updated) as { subscriptions?: unknown } | null)?.subscriptions == null
		)
			return updated.replace(/^subscriptions:[ \t]*$/m, 'subscriptions: []');
		return updated;
	}
	if (generated.length === 0) return raw;
	if (/^subscriptions:[ \t]*\[\][ \t]*$/m.test(raw))
		raw = raw.replace(/^subscriptions:[ \t]*\[\][ \t]*$/m, 'subscriptions:');
	const match = /^subscriptions:[ \t]*(?:#.*)?$/m.exec(raw);
	if (!match) {
		if (raw.trim() && !raw.endsWith('\n')) raw += '\n';
		return raw + 'subscriptions:\n' + block;
	}
	const after = match.index + match[0].length;
	const tail = raw.slice(after);
	const next = /^\S[^\n]*:/gm;
	const boundary = next.exec(tail);
	const position = boundary ? after + boundary.index : raw.length;
	return raw.slice(0, position).replace(/([^\n])$/, '$1\n') + block + raw.slice(position);
}

function writeProgramCue(program: PianolaProgram): string | null {
	if (program.remoteId)
		return 'Cue skipped for ' + program.id + ': CLI has no remote SSH file writer';
	if (!path.win32.isAbsolute(program.root))
		return 'Cue skipped for ' + program.id + ': root is not a local Windows path';
	const target = path.join(program.root, '.maestro', 'cue.yaml');
	fs.mkdirSync(path.dirname(target), { recursive: true });
	const raw = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : '';
	const updated = updateGeneratedCueYaml(raw, program);
	if (updated !== raw) writeCueYamlAtomicSync(target, updated);
	return null;
}

export async function pianolaProgramApply(options: {
	file: string;
	json?: boolean;
}): Promise<void> {
	ensurePianolaEnabled(options.json);
	let manifest: unknown;
	try {
		const content = fs.readFileSync(path.resolve(options.file), 'utf-8');
		manifest = /\.json$/i.test(options.file) ? JSON.parse(content) : yaml.load(content);
	} catch (error) {
		fail(
			`Could not load program file: ${error instanceof Error ? error.message : String(error)}`,
			options.json
		);
	}
	const programs =
		manifest && typeof manifest === 'object' && 'programs' in manifest
			? manifest.programs
			: undefined;
	if (!Array.isArray(programs))
		return fail('Program file must contain a programs array', options.json);
	const ids = new Set<string>();
	const candidates: PianolaProgram[] = [];
	for (const raw of programs) {
		const existing =
			raw && typeof raw === 'object' && 'id' in raw && typeof raw.id === 'string'
				? readPianolaPrograms().find((p) => p.id === raw.id)
				: undefined;
		if (!raw || typeof raw !== 'object' || Array.isArray(raw))
			return fail('Invalid program entry', options.json);
		const input = raw as Record<string, unknown>;
		const roles =
			input.roles && typeof input.roles === 'object' && !Array.isArray(input.roles)
				? (input.roles as Record<string, unknown>)
				: {};
		const mergedRoles: Record<string, unknown> = {};
		for (const [key, role] of Object.entries(roles)) {
			mergedRoles[key] =
				role && typeof role === 'object' && !Array.isArray(role)
					? {
							...role,
							agentId:
								('agentId' in role ? role.agentId : undefined) ?? existing?.roles[key]?.agentId,
						}
					: role;
		}
		const now = Date.now();
		const remoteId =
			typeof input.remoteId === 'string'
				? (readSshRemotes().find(
						(remote) => remote.id === input.remoteId || remote.name === input.remoteId
					)?.id ?? input.remoteId)
				: undefined;
		const candidate = validatePianolaProgram({
			...input,
			...(remoteId ? { remoteId } : {}),
			roles: mergedRoles,
			leadAgentId: (mergedRoles.lead as { agentId?: string } | undefined)?.agentId,
			status: existing?.status ?? input.status ?? 'active',
			createdAt: existing?.createdAt ?? now,
			updatedAt: existing?.updatedAt ?? now,
		});
		if (!candidate)
			return fail('Invalid program: ' + String(input.id ?? '(missing id)'), options.json);
		if (ids.has(candidate.id)) return fail('Duplicate program id: ' + candidate.id, options.json);
		ids.add(candidate.id);
		candidates.push(candidate);
	}
	let client: MaestroClient | undefined;
	const applied: PianolaProgram[] = [];
	const cueWarnings: string[] = [];
	try {
		for (let program of candidates) {
			const existing = readPianolaPrograms().find((p) => p.id === program.id);
			if (
				existing &&
				JSON.stringify(existing) === JSON.stringify(program) &&
				Object.values(program.roles).every((role) => !!role.agentId)
			) {
				applied.push(existing);
				const warning = writeProgramCue(existing);
				if (warning) cueWarnings.push(warning);
				continue;
			}
			// Local role agents run `maestro-cli pianola ...` from their own shell: hand them the
			// same CLI script and data dir Pianola gets, so a lead can save plans and raise asks.
			// A remote (SSH) role runs on another filesystem, where these Windows paths mean nothing.
			// A remote (SSH) role runs on another filesystem: its env comes from the manifest's
			// `remoteEnv` on the program (CLI wrapper path, data dir, and host as seen from there).
			const roleEnv: Record<string, string> | undefined = program.remoteId
				? program.remoteEnv
				: { MAESTRO_CLI_JS: process.argv[1] ?? '', MAESTRO_USER_DATA: getConfigDirectory() };
			program = { ...program, updatedAt: existing ? Date.now() : program.updatedAt };
			upsertPianolaProgram(program);
			for (const [key, role] of Object.entries(program.roles)) {
				if (role.agentId) {
					const old = existing?.roles[key];
					const configPatch: Record<string, unknown> = {};
					if (old?.model !== role.model) configPatch.customModel = role.model ?? null;
					if (old?.instructions !== role.instructions)
						configPatch.newSessionMessage = role.instructions ?? null;
					if (roleEnv) configPatch.customEnvVars = roleEnv;
					if (Object.keys(configPatch).length || (existing && existing.root !== program.root)) {
						if (!client) {
							client = new MaestroClient();
							await client.connect();
						}
						if (Object.keys(configPatch).length) {
							const result = await client.sendCommand<{ success: boolean; error?: string }>(
								{ type: 'update_session_config', sessionId: role.agentId, configPatch },
								'update_session_config_result'
							);
							if (!result.success) throw new Error(result.error ?? 'Failed to update role config');
						}
						if (existing && existing.root !== program.root) {
							const result = await client.sendCommand<{ success: boolean; error?: string }>(
								{ type: 'update_session_cwd', sessionId: role.agentId, newCwd: program.root },
								'update_session_cwd_result'
							);
							if (!result.success) throw new Error(result.error ?? 'Failed to update role root');
						}
					}
					continue;
				}
				if (!client) {
					client = new MaestroClient();
					await client.connect();
				}
				const result = await client.sendCommand<{
					success: boolean;
					sessionId?: string;
					error?: string;
				}>(
					{
						type: 'create_session',
						name: role.name,
						toolType: role.agentType ?? 'omp',
						cwd: program.root,
						...(role.model ? { customModel: role.model } : {}),
						...(role.instructions ? { newSessionMessage: role.instructions } : {}),
						...(roleEnv ? { customEnvVars: roleEnv } : {}),
						...(program.remoteId
							? {
									sessionSshRemoteConfig: {
										enabled: true,
										remoteId: program.remoteId,
										workingDirOverride: program.root,
									},
								}
							: {}),
					},
					'create_session_result'
				);
				if (!result.success || !result.sessionId)
					throw new Error(result.error ?? `No sessionId for ${program.id}:${key}`);
				program = {
					...program,
					roles: { ...program.roles, [key]: { ...role, agentId: result.sessionId } },
					...(key === 'lead' ? { leadAgentId: result.sessionId } : {}),
				};
				upsertPianolaProgram(program);
			}
			const warning = writeProgramCue(program);
			if (warning) cueWarnings.push(warning);
			applied.push(program);
		}
	} catch (error) {
		fail(
			`Program apply failed: ${error instanceof Error ? error.message : String(error)}`,
			options.json
		);
	} finally {
		client?.disconnect();
	}
	for (const warning of cueWarnings) console.error(warning);
	print(applied, options.json);
}

export function pianolaProgramList(options: { json?: boolean }): void {
	ensurePianolaEnabled(options.json);
	print(readPianolaPrograms(), options.json);
}
export function pianolaProgramShow(id: string, options: { json?: boolean }): void {
	ensurePianolaEnabled(options.json);
	const program = readPianolaPrograms().find((p) => p.id === id);
	if (!program) fail(`Program not found: ${id}`, options.json);
	print(program, options.json);
}
export function pianolaProgramStatus(
	id: string,
	status: 'active' | 'paused',
	options: { json?: boolean }
): void {
	ensurePianolaEnabled(options.json);
	const current = readPianolaPrograms().find((p) => p.id === id);
	if (!current) return fail('Program not found: ' + id, options.json);
	const updated =
		current.status === status ? current : { ...current, status, updatedAt: Date.now() };
	if (updated !== current) upsertPianolaProgram(updated);
	print(updated, options.json);
}

export interface EscalateOptions {
	title: string;
	detail: string;
	program?: string;
	agent?: string;
	tab?: string;
	severity?: PianolaAskSeverity;
	requestedAction?: string;
	distinct?: boolean;
	json?: boolean;
}
export function pianolaEscalate(options: EscalateOptions): void {
	ensurePianolaEnabled(options.json);
	if (!options.title?.trim() || !options.detail?.trim())
		fail('Title and detail are required', options.json);
	if (options.severity && !['low', 'medium', 'high', 'critical'].includes(options.severity))
		fail('Invalid severity', options.json);
	const now = new Date().toISOString();
	const ask: PianolaAsk = {
		id: generateUUID(),
		createdAt: now,
		updatedAt: now,
		title: options.title,
		detail: options.detail,
		severity: options.severity ?? 'medium',
		dedupeKey: `${options.agent ?? 'unknown'}:${options.program ?? 'global'}`,
		status: 'open',
		...(options.program ? { programId: options.program } : {}),
		...(options.agent ? { agentId: options.agent } : {}),
		...(options.tab ? { tabId: options.tab } : {}),
		...(options.requestedAction ? { requestedAction: options.requestedAction } : {}),
	};
	const result = dedupeAsk(readPianolaAsks(), ask, options.distinct);
	writePianolaAsks(result.asks);
	print(result.ask, options.json);
}
export function pianolaResolve(
	id: string,
	options: { option: string; note?: string; json?: boolean }
): void {
	ensurePianolaEnabled(options.json);
	if (!options.option?.trim()) fail('Resolution option is required', options.json);
	const asks = readPianolaAsks();
	const ask = asks.find((a) => a.id === id && a.status === 'open');
	if (!ask) return fail('Open ask not found: ' + id, options.json);
	const now = new Date().toISOString();
	const updated: PianolaAsk = {
		...ask,
		status: 'resolved',
		updatedAt: now,
		resolution: {
			option: options.option,
			...(options.note === undefined ? {} : { note: options.note }),
			resolvedAt: now,
		},
	};
	writePianolaAsks(asks.map((a) => (a.id === id ? updated : a)));
	print(updated, options.json);
}
export function pianolaDismiss(id: string, options: { json?: boolean }): void {
	ensurePianolaEnabled(options.json);
	const asks = readPianolaAsks();
	const ask = asks.find((a) => a.id === id && a.status === 'open');
	if (!ask) return fail('Open ask not found: ' + id, options.json);
	const updated: PianolaAsk = { ...ask, status: 'dismissed', updatedAt: new Date().toISOString() };
	writePianolaAsks(asks.map((a) => (a.id === id ? updated : a)));
	print(updated, options.json);
}
function brief() {
	const plans = readPianolaPlans();
	const runs = briefRunsForPlans(plans, readAgentRuns(), pianolaTaskAgentRunId);
	return derivePianolaBrief(
		readPianolaPrograms(),
		plans,
		readPianolaAsks(),
		readPianolaDecisions(),
		runs,
		new Date().toISOString(),
		readPianolaSupervisorTargets(),
		readPianolaProgramLoopMemo()
	);
}
export function pianolaNeedsMe(options: { json?: boolean }): void {
	ensurePianolaEnabled(options.json);
	print(brief().needsMe, options.json);
}
export function pianolaBrief(options: { json?: boolean }): void {
	ensurePianolaEnabled(options.json);
	print(brief(), options.json);
}
