export const discoveryPanel = `
<p id="flow-progress" class="hint">Step 1 of 4 · Choose a computer</p>
<button id="guide-back" type="button" hidden>Back</button>
<section id="pairing-panel" class="task" aria-labelledby="pair-heading" hidden>
<h2 id="pair-heading" tabindex="-1"></h2><p id="pair-status" role="status" aria-live="polite"></p>
<div id="pair-pin-entry" hidden><label for="pair-pin">Code shown on your other computer</label><div class="inline-field"><input id="pair-pin" inputmode="numeric" autocomplete="one-time-code" spellcheck="false" aria-describedby="pair-pin-help pair-error"><button id="pair-submit" class="primary" disabled>Continue</button></div><p id="pair-pin-help" class="hint">Enter all 6 digits.</p></div>
<p id="pair-error" class="field-error" role="alert"></p><div class="actions"><button id="pair-retry" class="primary" hidden>Try again</button><button id="pair-dismiss" hidden>Back to computers</button><button id="pair-cancel" hidden>Cancel</button><button id="pair-return" class="primary" hidden>Open Maestro</button><button id="pair-disconnect" hidden>Disconnect</button></div></section>
<section id="discovery-panel" aria-labelledby="discovery-heading">
<h2 id="discovery-heading" tabindex="-1">Choose your computer</h2><p id="discovery-intro">Find the computer running Maestro on your Tailscale network.</p>
<button id="discovery-tailnet" type="button" class="primary">Find my computer</button>
<p id="discovery-status" role="status" aria-live="polite">Looking for computers…</p><div id="discovered-hosts" class="host-cards" role="group" aria-labelledby="discovery-heading" aria-busy="true"></div><p id="discovery-empty" class="hint" hidden></p><button id="discovery-start" type="button">Search again</button></section>
<section id="connection-help" hidden><h2 id="help-heading" tabindex="-1">Can't find your computer?</h2><ol><li>Keep Maestro open on your other computer.</li><li>In Maestro, choose <strong>Connect another device</strong> and turn on access.</li><li>Connect both computers to the same Tailscale network.</li></ol><button id="help-search" type="button" class="primary">Search again</button><div class="alternative-actions"><button id="discovery-manual" type="button">Use a link or SSH</button><button id="open-invitation" type="button">Use an invitation</button><button id="open-diagnostics" type="button">Connection diagnostics</button></div></section>
<section id="invitation-page" hidden><h2 id="invitation-heading" tabindex="-1">Paste your invitation</h2><p>Copy the invitation from Maestro on the other computer.</p><label for="discovery-invitation">Invitation</label><textarea id="discovery-invitation" rows="4" spellcheck="false"></textarea><button id="discovery-import" type="button" class="primary">Find this computer</button></section>
<section id="discovery-details" hidden><h2 id="diagnostics-heading" tabindex="-1">Connection diagnostics</h2><label class="check"><input id="discovery-peers" type="checkbox" aria-describedby="discovery-peers-help"><span>Include my Tailscale devices</span></label><p id="discovery-peers-help" class="hint">Searches devices on your Tailscale network. Nothing connects until you choose a computer.</p><ul id="discovery-sources"></ul><button id="discovery-stop" type="button">Stop search</button>
<section id="pair-proof" hidden><h3>Paired computer</h3><p id="pair-identity" class="hint"></p><p id="pair-metadata" class="hint"></p><button id="pair-read" type="button" disabled>Check identity</button><button id="pair-forget" type="button">Forget pairing</button></section>
<section><h3>Maestro updates</h3><p id="connection-update-status" class="hint">Check here if the other computer reports a different Maestro version.</p><button id="connection-update-check" type="button">Check for updates</button><button id="connection-update-download" type="button" hidden>Download update</button><button id="connection-update-install" type="button" hidden>Restart and install</button></section></section>
<footer id="guide-options"><button id="guide-help" type="button">Can't find your computer?</button></footer>`;
